---
- hosts: all
  tasks:
   - name: installing docker
     yum:
      name: docker
      state: latest

   - name: starting the docker service
     service:
       name: docker
       state: started
       enabled: yes

